### PR TITLE
Rm Trace LInk

### PR DESCRIPTION
**Pull request by hinthornw**
When the write queue goes in, the run IDs will no longer be immediately available. 
Hide the link function until we bypass this.

### CODE REVIEW

**Comment by jacoblee93** [comment]
I had this in #139 as well but I was planning to rebase anyway - seems fine. Lot of formatting changes but looks like you just removed the button right?

Do we need to change the backend or can we just hide the button?

**Comment by hinthornw** [comment]
Na can just hide the button

**Comment by hinthornw** [comment]
You can just merge yours!

**Comment by jacoblee93** [comment]
Merged in a different PR

**Pull request closed without merging**
